language: cpp
matrix:
  include:
  - os: osx
  - os: osx
    osx_image: xcode8.3
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
    env:
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
before_install:
- eval "${MATRIX_EVAL}"
script:
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=${HOME}/local ..
- cmake --build . -- --jobs=2
- cmake --build . --target install
- ctest -V
branches:
  except:
  - /^v?\d+\.\d+/
notifications:
  email: false
  slack:
    secure: ovH2iJ8eVeIvGa2i1mHNF46VH6kuwbprIIUJqQa87aA0x4ZeD/4C7f76SZDDqLR9xUHcjB0U0hFdX8jL8F2LGcZbgdlyRuSSIg1/FPIeAbQv3XasB7BHM0GLiGcKtrrgHDIXFFQViQ+qa7CETDvHhTTqTGrRLISSlFiW2q4kU1gohxktkzGUwIvzF8Ia5W39M4s8fdF4gGafNjQJ/upN2ZPIohRfV4admZKteQuS/Azhx2IYtnKIMSU2f0LIRyHjpA8smSTOxVjj2p8CQIu6AN5WBxeyNV9YfZ2BrByZktshHLceLp7eapKX348Unc49jGtricKg4neVLLYzy3l7obdsWbkgkU0qe00APhX54apr28J0GSBFM9hCsioG9SXQ9KYfNb/k1XE6xrLcHtcP3qrfokCdNcrTnTKRJmc+7a5NXckPk4gOLZNn6HPIWuSKut8kjtXNZbc2pyMB5yGI73cztfbJAhW4z+RhTOrPv/VXKZlXwlFobAr9MkpLIp0LwdfdVITwQoz81Sg9wNstrezZMWVePMWhPeftLgAQYpH8hZ9IhaiLtRZWvwg48Azvt5/VSi8h0um1pVIkVtlAsGSp9F3liB6pSsMttaUageEG46yk4XtGM/Vsko9/uXk0mXaOs/ad1TAvQ0fxVSFJFRypoMsJoKEtKtPkb4tKNHI=
